name: Release builds

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  # Set release to prerelease first
  prerelease:
    name: Set Prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Prerelease
        uses: irongut/EditRelease@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ github.event.release.id }}
          prerelease: true

  # Main release job for all platforms
  release:
    needs: prerelease
    name: Release Standard
    runs-on: ubuntu-latest
    steps:

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo snap install zig --classic --beta
          docker pull crazymax/xgo:latest
          go install github.com/crazy-max/xgo@latest
          sudo apt install upx

      - name: Build
        run: |
          bash build.sh release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FRONTEND_REPO: ${{ vars.FRONTEND_REPO }}

      - name: Keep Minimal Assets
        run: |
          cd build/compress
          shopt -s nullglob
          for f in *; do
            case "$f" in
              openlist-linux-amd64.tar.gz|openlist-linux-arm64.tar.gz|openlist-windows-amd64.zip|openlist-windows-arm64.zip)
                ;;
              *)
                rm -f "$f"
                ;;
            esac
          done
          md5sum \
            openlist-linux-amd64.tar.gz \
            openlist-linux-arm64.tar.gz \
            openlist-windows-amd64.zip \
            openlist-windows-arm64.zip \
            > md5-windows-linux.txt

      - name: Upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: build/compress/*
          prerelease: false
          tag_name: ${{ github.event.release.tag_name }}
